jtype: Flow
version: '1'
with:
  port: 8080
  protocol: http
  cors: true
  title: 'Cerebro Embedding Flow'
  description: 'Text embedding pipeline for Project Cerebro context memory'

executors:
  - name: text_encoder
    uses: jinahub://JinaEmbeddingExecutor
    with:
      model_name: 'jina-embeddings-v2-base-en'
      device: 'cpu'
      batch_size: 32
      max_length: 512
    replicas: 1

  - name: context_processor
    uses: CerebroContextProcessor
    with:
      vector_dim: 768
      similarity_threshold: 0.7
    replicas: 1