version: '3.8'

services:
  # Infisical secrets management
  infisical:
    image: infisical/infisical:latest
    container_name: infisical-secrets
    restart: unless-stopped
    environment:
      - INFISICAL_PROJECT_ID=73c2f3cb-c922-4a46-a333-7b96fbc6301a
      - INFISICAL_ENVIRONMENT=production
    volumes:
      - ./infisical:/app/infisical
    networks:
      - hft-network
    command: ["infisical", "run", "--projectId", "73c2f3cb-c922-4a46-a333-7b96fbc6301a", "--env", "production", "--", "sleep", "infinity"]

  hft-ninja:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solana-hft-ninja
    restart: unless-stopped
    depends_on:
      - infisical
    env_file:
      - .env
    environment:
      # Infisical integration
      - INFISICAL_PROJECT_ID=73c2f3cb-c922-4a46-a333-7b96fbc6301a
      - INFISICAL_ENVIRONMENT=production
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./data:/app/data
      - ./infisical:/app/infisical
    ports:
      - "8080:8080"
    networks:
      - hft-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - hft-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - hft-network

volumes:
  prometheus_data:
    driver: local
  grafana-storage:
    driver: local

networks:
  hft-network:
    driver: bridge