# Prometheus Configuration for Solana HFT Ninja 2025.07
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'hft-ninja-devnet'
    environment: 'devnet'
    security_provider: 'chainguard'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # HFT Application Metrics (LIVE INSTANCE)
  - job_name: 'hft-ninja-live'
    static_configs:
      - targets: ['host.docker.internal:9090']  # Real HFT Ninja metrics server
    scrape_interval: 5s
    metrics_path: /metrics

  # HFT Application API Health
  - job_name: 'hft-ninja-api'
    static_configs:
      - targets: ['host.docker.internal:8080']  # Real HFT Ninja API server
    scrape_interval: 15s
    metrics_path: /health
    
  # Prometheus Self-Monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    
  # System Metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s
