# 🚀 Solana HFT Ninja - Devnet Configuration
# Safe testing environment with proper TOML structure

[solana]
rpc_url = "https://api.devnet.solana.com"
ws_url = "wss://api.devnet.solana.com"
rpc_timeout_ms = 10000

[wallet]
private_key_path = "config/wallet.json"
keypair_path = "config/wallet.json"

[trading]
initial_balance_sol = 3.0
max_position_size_sol = 0.5
max_slippage_bps = 200  # 2%
min_profit_threshold_bps = 50  # 0.5%
risk_limit_bps = 500  # 5%

[strategy]
strategy_mode = "sandwich"
update_interval_ms = 100
order_book_depth = 20
spread_bps = 10  # 0.1%

[risk]
stop_loss_bps = 300  # 3%
take_profit_bps = 200  # 2%
max_drawdown_bps = 1000  # 10%
risk_limit_bps = 500  # 5%

[logging]
rust_log = "info"
log_level = "info"
log_file_path = "logs/hft.log"

[monitoring]
metrics_port = 8080
health_check_interval_ms = 30000
enable_ddos_protection = true
rate_limit_rps = 100
